POST http://localhost:8000/relative/add_patient
Token:d1b4f3355d6810fd2b7241ef95b893fd467269204e6f762031322032303a33393a33302032303231
Content-Type: application/json

{
  "PatientBd": "1998-01-04",
  "PRName": "Derman",
  "PRNum": "05378270553",
  "PRName2": "Dilek",
  "PRNum2": "05318874348",
  "PatientGender": "M",
  "PatientAddress": "Karaagac Konarli Mahallesi 6. Sokak no 8",
  "PatientTc": "10952336010",
  "PatientName": "Ali",
  "PatientSurname": "Akgol",
  "PRSurname": "Keskinkilinc",
  "PRSurname2": "Yayman"
}